### PR TITLE
Add Mongodb

### LINKED ISSUE #4: Add database
As an administrator,
I like to connect a database,
so that I can easier scale and maintain this application.

- MongoDB 
- Atlas

### PR DESCRIPTION
**Pull request by lmachens**
Fix #4

### CODE REVIEW

**Review by manuelsanchez2 — APPROVED** [review]
gj!

**Review by mpagels — APPROVED** [review]
incredible job!

**Review by manuelpapa — APPROVED** [review]
yay!

**Review by rheimers — APPROVED** [review]
YES MAN!

**Comment by DrBennemin** [comment]
The absolute overhammer. ⛏🐜🐜🐜🐜🐜🐜  <3 vielen Dank!

**Pull request merged**
